# Module 5 - Assignment 2
## Wilds, Charles
### More Data Wrangling

```{r}
library(tidyverse)
library(readr)
tuition_cost <- read_csv("tuition_cost.csv")
```

### Part 1 – Creating tidy data using tidyr

```{r}

Tuition = pivot_longer(tuition_cost,c('2017','2018','2019','2020'),names_to = 'Year',values_to = 'Tuition')

Tuition = separate(Tuition,Tuition,into=c("Instate","Outstate"),sep='/')
```

###  Part 2 – North Carolina Schools

```{r}
library(ggplot2)
Public = filter(Tuition, type == "Public" & state_code == "NC" & degree_length == "4 Year")

ggplot(data=Public, aes(x=Year,y=Instate, color=name)) +
  geom_point() +
  labs(y="Cost in $", x="Year", title="In-State Tuition for North Carolina Schools") +
  theme(legend.title = element_blank())
  

UNC = filter(Public,grepl("University of North Carolina",name))

ggplot(data=UNC, aes(x=Year,y=Instate, color=name)) +
  geom_point() +
  labs(y="Cost in $", x="Year", title="In-State Tuition for UNC Schools") +
  theme(legend.position="bottom") +
  theme(legend.title = element_blank()) +
  guides(colour = guide_legend(nrow = 4))



```

### Part 3 – Additional Universities

```{r}
Colorado = filter(Tuition, type == "Public" & state_code == "CO" & degree_length == "4 Year")

SouthCarolina = filter(Tuition, type == "Public" & state_code == "SC" & degree_length == "2 Year")

ggplot(data=Colorado, aes(x=Year,y=Outstate, color=name)) +
  geom_point() +
  labs(y="Cost in $", x="Year", title="Out of State Tuition for Colorado Schools") +
  theme(legend.title = element_blank())

ggplot(data=SouthCarolina, aes(x=Year,y=Outstate, color=name)) +
  geom_point() +
  labs(y="Cost in $", x="Year", title="Out of State Tuition for South Carolina Schools") +
  theme(legend.title = element_blank())
  
```

